server:
  port: 8761
# eureka \u7684\u76F8\u5173\u914D\u7F6E
eureka:
  instance:
    hostname: localhost
  client:
    ## \u4EE5\u4E0B\u4E24\u4E2A\u914D\u7F6E\u7684false\u8868\u793A\u81EA\u5DF1\u662F\u4E00\u4E2Aeureka server\u7AEF
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/