spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
server:
  servlet:
    context-path: /limpid

management:
  # \u7AEF\u70B9\u4FE1\u606F\u63A5\u53E3\u4F7F\u7528\u7684\u7AEF\u53E3\uFF0C\u4E3A\u4E86\u548C\u4E3B\u7CFB\u7EDF\u63A5\u53E3\u4F7F\u7528\u7684\u7AEF\u53E3\u8FDB\u884C\u5206\u79BB
  server:
    port: 8090
    servlet:
      context-path: /server
  # \u7AEF\u70B9\u5065\u5EB7\u60C5\u51B5\uFF0C\u9ED8\u8BA4\u503C"never"\uFF0C\u8BBE\u7F6E\u4E3A"always"\u53EF\u4EE5\u663E\u793A\u786C\u76D8\u4F7F\u7528\u60C5\u51B5\u548C\u7EBF\u7A0B\u60C5\u51B5
  endpoint:
    health:
      show-details: always
  # \u8BBE\u7F6E\u7AEF\u70B9\u66B4\u9732\u7684\u54EA\u4E9B\u5185\u5BB9\uFF0C\u9ED8\u8BA4["health","info"]\uFF0C\u8BBE\u7F6E"*"\u4EE3\u8868\u66B4\u9732\u6240\u6709\u53EF\u8BBF\u95EE\u7684\u7AEF\u70B9
  endpoints:
    web:
      exposure:
        include: '*'